namespace: task-manager

backend:
  replicaCount: 1
  image:
    repository: task-manager-backend
    tag: dev
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
  env:
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/microservices_db

frontend:
  replicaCount: 1
  image:
    repository: task-manager-frontend
    tag: dev
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  database: microservices_db
  username: postgres
  password: postgres
  storage: 1Gi
