apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: task-manager-backend
    newName: task-manager-backend
    newTag: dev

  - name: task-manager-frontend
    newName: task-manager-frontend
    newTag: dev
